// @generated by protobuf-ts 2.8.2
// @generated from protobuf file "rental.proto" (package "rental.v1", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message rental.v1.CreateTripRequest
 */
export interface CreateTripRequest {
    /**
     * @generated from protobuf field: string start = 1;
     */
    start: string;
}
/**
 * @generated from protobuf message rental.v1.CreateTripResponse
 */
export interface CreateTripResponse {
}
// @generated message type with reflection information, may provide speed optimized methods
class CreateTripRequest$Type extends MessageType<CreateTripRequest> {
    constructor() {
        super("rental.v1.CreateTripRequest", [
            { no: 1, name: "start", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CreateTripRequest>): CreateTripRequest {
        const message = { start: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<CreateTripRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateTripRequest): CreateTripRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string start */ 1:
                    message.start = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateTripRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string start = 1; */
        if (message.start !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.start);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message rental.v1.CreateTripRequest
 */
export const CreateTripRequest = new CreateTripRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateTripResponse$Type extends MessageType<CreateTripResponse> {
    constructor() {
        super("rental.v1.CreateTripResponse", []);
    }
    create(value?: PartialMessage<CreateTripResponse>): CreateTripResponse {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<CreateTripResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateTripResponse): CreateTripResponse {
        return target ?? this.create();
    }
    internalBinaryWrite(message: CreateTripResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message rental.v1.CreateTripResponse
 */
export const CreateTripResponse = new CreateTripResponse$Type();
/**
 * @generated ServiceType for protobuf service rental.v1.TripService
 */
export const TripService = new ServiceType("rental.v1.TripService", [
    { name: "CreateTrip", options: {}, I: CreateTripRequest, O: CreateTripResponse }
]);
